// components/links.vue
<template>
    <v-btn
        @click="(snackbar = true), copyclipboard('2lay')"
        block
        target="_blank"
        class="text-center btn-custom btn-spacing hover-animation"
        style="
            background-color: rgba(86, 96, 234, 0.212);
            border: 1px solid rgba(86, 96, 234, 0.412);
            overflow: visible;
        "
    >
        <span /><font-awesome-icon icon="fa-brands fa-discord" /> &nbsp;Discord&nbsp;
        <div style="color: #979797">@2lay</div>
        <v-snackbar class="snackbar-custom" v-model="snackbar" color="rgba(0, 0, 0, 0.7)">
            <div style="color: white">Copied username to clipboard.</div>

            <template v-slot:actions>
                <v-btn color="hsl(var(--primary))" variant="tonal" @click="snackbar = false" class="hover-animation btn-custom"> Close </v-btn>
            </template>
        </v-snackbar>
    </v-btn>
    <div v-for="item in links_socials" :key="item.name">
        <v-btn
            block
            :href="item.link"
            class="text-center btn-custom btn-spacing hover-animation"
            :style="'background-color: rgba(' + item.rgb + ', 0.212); border: 1px solid rgba(' + item.rgb + ', 0.412);'"
        >
            <template v-if="item.icon.startsWith('mdi')">
                <span :class="item.icon"></span>
            </template>
            <template v-else>
                <font-awesome-icon :icon="item.icon" />
            </template>
            &nbsp;{{ item.name }}&nbsp;
            <div style="color: #979797">{{ item.domain }}</div>
        </v-btn>
    </div>
</template>

<script setup>
import { ref } from 'vue'

const links_socials = ref([
    {
        rgb: '220, 27, 37',
        icon: 'fa-brands fa-lastfm',
        name: 'Last.fm',
        domain: '@twolay',
        link: 'https://www.last.fm/user/twolay',
    },
    {
        rgb: '147, 147, 147',
        icon: 'fa-brands fa-github',
        name: 'GitHub',
        domain: '@2lay',
        link: 'https://github.com/2lay',
    },
    {
        rgb: '247, 15, 27',
        icon: 'fa-brands fa-youtube ',
        name: 'YouTube',
        domain: '@2lay',
        link: 'https://www.youtube.com/channel/UC-jrEls9AJslFXMyonCd09w',
    },
    {
        rgb: '19, 115, 163',
        icon: 'fa-brands fa-steam',
        name: 'Steam',
        domain: '@2lay',
        link: 'https://steamcommunity.com/id/2lay',
    },
    {
        rgb: '255, 149, 187',
        icon: 'mdi mdi-card-account-details',
        name: 'Pronouns.page',
        domain: '@2lay',
        link: 'https://en.pronouns.page/@2lay',
    },
])
</script>

<script>
export default {
    data: () => ({
        snackbar: false,
        text: 'Copied username to clipboard.',
        timeout: 2000,
    }),
    methods: {
        copyclipboard(text) {
            navigator.clipboard.writeText(text)
        },
    },
}
</script>

// app/contact/links.tsx
"use client";

import Link from "next/link";
import { useState } from "react";

const contactLinks = [
    {
        href: "#",
        title: "Discord",
        username: "2lay",
        color: { r: 149, g: 160, b: 255 },
        secondaryColor: { r: 104, g: 112, b: 182 },
    },
    {
        href: "https://t.me/twolay",
        title: "Telegram",
        username: "twolay",
        color: { r: 149, g: 189, b: 255 },
        secondaryColor: { r: 106, g: 135, b: 182 },
    },
    {
        href: "mailto:ashley@2lay.net",
        title: "Mail",
        username: "ashley@2lay.net",
        color: { r: 240, g: 168, b: 208 },
        secondaryColor: { r: 170, g: 119, b: 147 },
    },
    {
        href: "https://last.fm/user/twolay",
        title: "Last.fm",
        username: "twolay",
        color: { r: 246, g: 117, b: 168 },
        secondaryColor: { r: 184, g: 87, b: 126 },
    },
    {
        href: "https://youtube.com/@2lay",
        title: "YouTube",
        username: "2lay",
        color: { r: 255, g: 113, b: 113 },
        secondaryColor: { r: 194, g: 86, b: 86 },
    },
    {
        href: "https://steamcommunity.com/id/2lay",
        title: "Steam",
        username: "2lay",
        color: { r: 177, g: 188, b: 230 },
        secondaryColor: { r: 145, g: 153, b: 189 },
    },
    {
        href: "https://github.com/2lay",
        title: "GitHub",
        username: "2lay",
        color: { r: 175, g: 175, b: 175 },
        secondaryColor: { r: 128, g: 128, b: 128 },
    },
    {
        href: "https://modrinth.com/user/2lay",
        title: "Modrinth",
        username: "2lay",
        color: { r: 205, g: 242, b: 202 },
        secondaryColor: { r: 153, g: 184, b: 151 },
    },
    {
        href: "https://www.curseforge.com/members/2lay",
        title: "Curseforge",
        username: "2lay",
        color: { r: 255, g: 200, b: 152 },
        secondaryColor: { r: 190, g: 149, b: 114 },
    },
];


export default function Links() {
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText("2lay");
        setCopied(true);
        setTimeout(() => setCopied(false), 3000);
    };

    return (
        <div className="flex flex-col gap-y-3 mt-3 max-w-96">
            {contactLinks.map((link, index) => (
                <div key={index} className="flex flex-col space-y-2">
                    <Link
                        href={link.href}
                        className={`flex justify-between items-center space-x-2 px-4 py-2 transition-all duration-300 ease-in-out hover:shadow-[5px_5px_0px_0px_var(--shadow-color)]`}
                        style={{
                            '--bg-color': `rgba(${link.color.r}, ${link.color.g}, ${link.color.b}, 0.2)`,
                            '--bg-hover-color': `rgba(${link.color.r}, ${link.color.g}, ${link.color.b}, 0.3)`,
                            '--text-color': `rgb(${link.color.r}, ${link.color.g}, ${link.color.b})`,
                            '--shadow-color': `rgb(${link.color.r}, ${link.color.g}, ${link.color.b})`,
                            backgroundColor: 'var(--bg-color)',
                            color: 'var(--text-color)',
                        }}
                        onClick={link.title === "Discord" ? handleCopy : undefined}
                    >
                        <span>{link.title === "Discord" && copied ? "Copied username!" : link.title}</span>
                        <span 
                            className="font-semibold"
                            style={{ color: `rgb(${link.secondaryColor.r}, ${link.secondaryColor.g}, ${link.secondaryColor.b})` }}
                        >
                            {link.username}
                        </span>
                    </Link>
                </div>
            ))}
        </div>
    );
}
