// pages/contact.vue
<template>
  <v-app class="hero">
    <v-container class="fill-height">
      <v-responsive class="align-center text-center fill-height">
        <v-card class="card-home card-style">
          <h1 class="text-h3 font-weight-bold animated-text">Contact me</h1>
          <p class="code-text">
            Have a question? Feel free to reach out!<br />You can email me at
            <strong>mail@2lay.net</strong><br />You can also message me on
            Discord at <strong>2lay</strong>
          </p>
        </v-card>
      </v-responsive>
    </v-container>
  </v-app>
</template>

<script setup lang="ts">
useSeoMeta({
  title: '2lay.net | Contact',
  ogTitle: '2lay.net | Contact',
  description: 'Need to contact me? Here are all the ways you can reach me.',
  ogDescription: 'Need to contact me? Here are all the ways you can reach me.',
  twitterCard: 'summary_large_image',
  themeColor: '#d754ff',
})
</script>

// app/contact/page.tsx
import Links from "./links";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "2lay.net - contact",
    description: "wanna contact me?",
    twitter: {
        card: "summary_large_image",
        title: "2lay.net - contact",
        description: "wanna contact me?",
        images: ["https://github.com/2lay.png"],
    },
};

export default function Home() {
    return (
        <main className="pt-8">
            <div className="text-neutral-100 px-5 flex-grow text-lg">
                <div className="flex flex-col gap-y-6">
                    <div>
                        <p className="text-3xl pb-2">
                            <a className="font-bold">$</a> contact me
                        </p>
                        <p>Here are the ways you can contact me:</p>
                        <Links />
                    </div>
                </div>
            </div>
        </main>
    );
}
